// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

// Generated query constants. None of these may be reported: they are the output of the workflow
// the guard tells people to follow, and reporting them told 27 repositories to fix files that
// running `sqlc generate` would immediately recreate.
//
// This file lives in internal/db rather than sqlc/ on purpose. Every *-core-postgres repo in the
// fleet points sqlc's `out:` here, so a guard that recognises only a directory named sqlc/
// recognises nothing that actually exists.

const getSession = `-- name: GetSession :one
SELECT id, identity_id, jti FROM sessions WHERE jti = $1
`

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE jti = $1
`

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, identity_id, jti) VALUES ($1, $2, $3)
`
