# Compliant fixture for controls/ci-identity.yaml.
#
# Exercises all three shapes the checker has to read, because a fixture that only covers the easy one
# would let a parser regression through on the other two:
#   1. an inline list inside a jsonencode'd assume_role_policy
#   2. a `condition` block in an aws_iam_policy_document
#   3. a `for`-generated local, where the two owner spellings come from the BINDING rather than from
#      the pattern literal - the case that crashed the first version of the detector
#
# Not applied to anything and not a module: the checker reads .tf text, so this needs to be
# representative rather than deployable.

locals {
  oidc_provider_sub = "token.actions.githubusercontent.com:sub"

  # Shape 3. One literal per subject, both owner spellings generated by iterating the binding, so the
  # classic and immutable forms cannot drift apart (CID-0002 is satisfied by construction).
  caller_subs = flatten([
    for o in var.caller_owners : [
      for owner in [o, "${o}@${var.caller_owner_ids[o]}"] : [
        "repo:${owner}/*:ref:refs/heads/main",
        "repo:${owner}/*:pull_request",
      ]
    ]
  ])
}

# Shape 1. Owner-wide role: the repository segment is a bare `*` and the pinned owner id carries the
# trust boundary, which is what CID-0004 permits for a collective grant.
resource "aws_iam_role" "owner_wide" {
  name = "fixture-owner-wide"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = "sts:AssumeRoleWithWebIdentity"
      Condition = {
        StringLike = {
          (local.oidc_provider_sub) = [
            "repo:${var.github_org}/*:ref:refs/heads/main",
            "repo:${var.github_org}@${var.github_org_id}/*:ref:refs/heads/main",
          ]
        }
      }
    }]
  })
}

# Shape 1, repository-scoped. The immutable pattern wildcards the NAME and pins the ID, so a rename
# keeps this working; the classic pattern beside it covers the repository until it adopts the
# immutable format. Both reach the same subject, as CID-0002 requires.
resource "aws_iam_role" "single_repo" {
  name = "fixture-single-repo"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = "sts:AssumeRoleWithWebIdentity"
      Condition = {
        StringLike = {
          (local.oidc_provider_sub) = [
            "repo:${var.github_org}/${var.app_repo}:environment:production",
            "repo:${var.github_org}@${var.github_org_id}/*@${var.app_repo_id}:environment:production",
          ]
        }
      }
    }]
  })
}

# Shape 2.
data "aws_iam_policy_document" "publish_assume" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRoleWithWebIdentity"]

    condition {
      test     = "StringLike"
      variable = "token.actions.githubusercontent.com:sub"
      values = [
        "repo:${var.github_org}/${var.app_repo}:ref:refs/heads/main",
        "repo:${var.github_org}@${var.github_org_id}/*@${var.app_repo_id}:ref:refs/heads/main",
      ]
    }
  }
}

# An EKS-issuer subject, present deliberately. GitHub's claim change cannot affect it - different
# issuer, different grammar, no `repo:` prefix - so the checker must leave it alone. If a future
# version starts reporting it, this fixture fails and says why.
data "aws_iam_policy_document" "irsa" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRoleWithWebIdentity"]

    condition {
      test     = "StringEquals"
      variable = "oidc.eks.eu-west-1.amazonaws.com/id/EXAMPLE:sub"
      values   = ["system:serviceaccount:kube-system:fixture-sa"]
    }
  }
}
