#!/usr/bin/env python3
"""Enforce that a service's OpenAPI generator is wired to the canonical library.

WHY THIS EXISTS. Every repository in the fleet that generates its contract from Go
annotations had a broken generator, and no CI job ran one, so nothing reported it:

  - eleven repos sourced "${SCRIPT_DIR}/../../../scripts/lib/swagger.sh", which resolves
    to services/scripts/lib/swagger.sh - a file that has never existed. Under
    `set -euo pipefail` the failed source aborted before swag ran, so those repos
    generated NOTHING and shipped whatever spec was last produced by hand.
  - six repos vendored their own copy of the library, in three byte-different variants.
    All six resolved the shared normalizer to a directory that does not contain it, and
    the caller discarded that failure with `2>/dev/null` and `|| true`, so swag and
    swagger2openapi ran and only normalization was skipped - silently.

Both shapes are STATIC and are what this script refuses. The dynamic half - that the
generator actually runs, and that normalization actually executes rather than being
skipped - is asserted by the workflow step that runs the generator, because only running
it can prove that.

Exit 0 when the wiring is sound, 1 on a violation, 2 when the repo cannot be classified.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# The canonical library, and the only path a caller may source it from. It ships in the
# same Go module as the openapi-normalize binary it runs, so the two are one versioned
# unit and cannot drift apart.
CANONICAL_SUFFIX = "tooling/openapi/lib/swagger.sh"

# A caller that reaches outside its own repository. This is the Category A defect: in a
# multi-repo fleet with no root git repository such a path exists on a workstation and in
# no CI checkout, so it can only ever have worked locally.
ESCAPING_SOURCE = re.compile(r"^\s*(?:source|\.)\s+.*\.\./\.\./\.\.", re.M)

# Re-vendoring. Six copies in three variants is how the fleet got here, so a local library
# is refused outright rather than compared against the canonical one.
VENDORED_LIB = "scripts/lib/swagger.sh"

# The specific line that hid this for as long as it lasted. Refused in the caller so it
# cannot be reintroduced there; the canonical library no longer contains it.
SWALLOWED_NORMALIZE = re.compile(
    r"(ensure_openapi_normalize[^\n]*2>\s*/dev/null)"
    r"|(_OPENAPI_NORMALIZE_BIN[^\n]*\|\|\s*true)"
    r"|(openapi-normalize[^\n]*\|\|\s*true)"
)

# The idiom that silently swallows a failed lookup. Under `set -e` the `:` builtin returns
# 0 even when its command substitution fails, so the variable is left empty and the script
# carries on - the same silent-skip shape this whole gate exists to remove.
SWALLOWING_ASSIGN = re.compile(r"^\s*:\s+\"\$\{SHARED_GO_DIR:=", re.M)


def fail(msg: str, path: Path | None = None) -> None:
    where = f"file={path}::" if path else "::"
    print(f"::error {where}{msg}" if path else f"::error::{msg}")


def check_repo(repo: Path) -> int:
    caller = repo / "scripts" / "swagger.sh"
    vendored = repo / VENDORED_LIB
    rc = 0

    if not caller.is_file():
        # Category C. auth-service generates from platform/openapicontract via
        # `make openapi-contract` and correctly has no swagger.sh. That is a different
        # engine, not an absence of one, and it owns its own gate
        # (openapi-contract-check). Accepting "no swagger.sh" unconditionally would give
        # every repo a way out of this gate by deleting one file, so the alternative
        # engine has to be POSITIVELY identified.
        makefile = repo / "Makefile"
        mk = makefile.read_text(encoding="utf-8", errors="replace") if makefile.is_file() else ""
        if re.search(r"^openapi-contract-check\s*:", mk, re.M):
            print(
                "::notice::no scripts/swagger.sh; this repo generates via the "
                "openapicontract engine and is gated by its own openapi-contract-check."
            )
            return 0
        fail(
            "this repo declares a REST interface but has no OpenAPI generator: no "
            "scripts/swagger.sh and no `openapi-contract-check` make target. A service "
            "whose spec is not generated by anything cannot be kept in step with its code."
        )
        return 1

    text = caller.read_text(encoding="utf-8", errors="replace")

    if vendored.is_file():
        fail(
            f"{VENDORED_LIB} is a vendored copy of the shared generator library. Six repos "
            f"carried one, in three byte-different variants, and all six silently skipped "
            f"normalization. Delete it and source the canonical library from "
            f"platform-shared-go instead.",
            vendored,
        )
        rc = 1

    if ESCAPING_SOURCE.search(text):
        fail(
            "scripts/swagger.sh sources a path outside this repository (../../..). That "
            "path is not present in a CI checkout of this repo alone, so the generator "
            "cannot run here. Source the canonical library from platform-shared-go.",
            caller,
        )
        rc = 1

    if CANONICAL_SUFFIX not in text:
        fail(
            f"scripts/swagger.sh does not source the canonical library "
            f"({CANONICAL_SUFFIX} from platform-shared-go). Every generator in the fleet "
            f"must run the same library, which ships with the normalizer it invokes.",
            caller,
        )
        rc = 1

    m = SWALLOWED_NORMALIZE.search(text)
    if m:
        fail(
            f"scripts/swagger.sh suppresses a normalizer failure ({m.group(0).strip()!r}). "
            f"Normalization decides field naming and the response envelope, so a spec "
            f"generated without it misdescribes the service and breaks generated clients. "
            f"It must fail loudly, never be skipped quietly.",
            caller,
        )
        rc = 1

    if SWALLOWING_ASSIGN.search(text):
        fail(
            "scripts/swagger.sh resolves SHARED_GO_DIR with `: \"${SHARED_GO_DIR:=$(...)}\"`. "
            "Under `set -e` the `:` builtin returns 0 even when its command substitution "
            "fails, leaving the path empty and continuing. Use a plain assignment so an "
            "unresolvable library aborts the script.",
            caller,
        )
        rc = 1

    if rc == 0:
        print(f"OpenAPI generator wiring OK: {caller} sources the canonical library.")
    return rc


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("repos", nargs="*", default=["."], help="service repo roots to check")
    args = ap.parse_args()

    rc = 0
    for r in args.repos or ["."]:
        p = Path(r).resolve()
        if not p.is_dir():
            print(f"::error::not a directory: {p}")
            return 2
        rc |= check_repo(p)
    return rc


if __name__ == "__main__":
    sys.exit(main())
