#!/usr/bin/env python3
"""Self-test for the org-versus-tenant vocabulary gate.

This test validates both enforcement and exception handling:
1. That "tenant" usage is caught as violations
2. That declared exceptions are properly respected
3. That the guard correctly excludes its own checkout when run on external repositories

The shapes tested are representative of real usage patterns across the fleet:
- Variable names with "tenant"
- Comments containing "tenant"
- Documentation text with "tenant"
- ADR filenames (immutable published records)
- Generated protobuf files
- Multi-tenancy architectural discussion
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CHECKER = REPO / "scripts" / "check-org-vocabulary.py"

FAILURES: list[str] = []


def expect(condition: bool, message: str) -> None:
    if not condition:
        FAILURES.append(message)


def run_checker(root: Path) -> tuple[int, str]:
    """Run the org vocabulary checker on the given root directory."""
    proc = subprocess.run(
        [sys.executable, str(CHECKER), "--repo-root", str(root)],
        capture_output=True, text=True,
    )
    return proc.returncode, proc.stdout + proc.stderr


def create_test_repo_with_violations(tmp_dir: Path) -> None:
    """Create a test repository with various tenant usage violations."""
    
    # Python file with tenant in variables and comments
    py_file = tmp_dir / "service.py"
    py_file.write_text('''
# This service handles tenant data processing
class TenantProcessor:
    def __init__(self, tenant_id: str):
        self.tenant_id = tenant_id  # Store the tenant identifier
        
    def process_tenant_data(self, tenant_data):
        """Process data for a specific tenant."""
        return tenant_data.upper()
''')

    # Go file with tenant usage
    go_file = tmp_dir / "handler.go"
    go_file.write_text('''
package main

import "fmt"

// HandleTenant processes requests for a tenant
func HandleTenant(tenantID string) {
    fmt.Printf("Processing for tenant: %s\\n", tenantID)
}
''')
    
    # Documentation with tenant usage
    doc_file = tmp_dir / "docs" / "api.md"
    doc_file.parent.mkdir(exist_ok=True)
    doc_file.write_text('''
# API Documentation

This API supports tenant-based access control.

## Tenant Endpoints

- GET /tenant/{id} - Get tenant information
- POST /tenant - Create new tenant
''')


def create_test_repo_with_exceptions(tmp_dir: Path) -> None:
    """Create a test repository with legitimate exceptions that should pass."""
    
    # ADR file (should be excepted)
    adr_file = tmp_dir / "docs" / "ADR-0020-multi-tenant-isolation.md"
    adr_file.parent.mkdir(exist_ok=True)
    adr_file.write_text('''
# ADR-0020: Multi-Tenant Isolation

## Context
We need to ensure proper tenant isolation in our multi-tenant architecture.
''')
    
    # Architectural documentation about multi-tenancy (should be excepted)
    arch_file = tmp_dir / "docs" / "architecture.md"
    arch_file.write_text('''
# Architecture Overview

## Multi-Tenancy Design

Our platform uses a multi-tenant architecture where each tenant's data is isolated.
''')
    
    # Generated protobuf file (should be excepted)
    pb_file = tmp_dir / "api" / "service.pb.go"
    pb_file.parent.mkdir(exist_ok=True)
    pb_file.write_text('''
// Code generated by protoc-gen-go. DO NOT EDIT.
package api

type TenantRequest struct {
    TenantId string
}
''')
    
    # Regular code using "org" (should pass)
    code_file = tmp_dir / "service.py"
    code_file.write_text('''
class OrgProcessor:
    def __init__(self, org_id: str):
        self.org_id = org_id
        
    def process_org_data(self, org_data):
        """Process data for a specific organization."""
        return org_data.upper()
''')


def test_violations_are_detected() -> None:
    """Test that tenant usage violations are properly detected."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        create_test_repo_with_violations(tmp_path)
        
        exit_code, output = run_checker(tmp_path)
        
        expect(exit_code == 1, f"violations should cause exit code 1, got {exit_code}")
        expect("::error" in output, f"should report errors, got: {output}")
        expect("tenant_id" in output, f"should detect tenant_id variable: {output}")
        expect("TenantProcessor" in output, f"should detect TenantProcessor class: {output}")
        expect("HandleTenant" in output, f"should detect HandleTenant function: {output}")


def test_exceptions_are_respected() -> None:
    """Test that declared exceptions are properly respected."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        create_test_repo_with_exceptions(tmp_path)
        
        exit_code, output = run_checker(tmp_path)
        
        expect(exit_code == 0, f"excepted usage should cause exit code 0, got {exit_code}: {output}")
        expect("::error" not in output, f"should not report errors for exceptions: {output}")
        expect("OK" in output, f"should report success: {output}")


def test_mixed_violations_and_exceptions() -> None:
    """Test a repository with both violations and valid exceptions."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        
        # Add both violations and exceptions
        create_test_repo_with_violations(tmp_path)
        create_test_repo_with_exceptions(tmp_path)
        
        exit_code, output = run_checker(tmp_path)
        
        expect(exit_code == 1, f"should fail due to violations despite exceptions, got {exit_code}")
        
        # Should detect violations in non-excepted files
        expect("service.py" in output, f"should detect violations in service.py: {output}")
        expect("handler.go" in output, f"should detect violations in handler.go: {output}")
        
        # Should not complain about excepted files
        expect("ADR-0020" not in output, f"should not flag ADR files: {output}")
        expect("*.pb.go" not in output, f"should not flag protobuf files: {output}")


def test_harness_checkout_exclusion() -> None:
    """Test that the checker excludes its own checkout when run on external repos."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        
        # Create a fake external repo with no violations
        (tmp_path / "main.go").write_text('package main\n\nfunc main() {\n    // org-based code\n}\n')
        
        # Create a fake ci-workflows checkout inside it (simulating CI harness)
        ci_checkout = tmp_path / ".org-tools" 
        ci_checkout.mkdir()
        
        # Create the scripts directory and checker file to be detected
        scripts_dir = ci_checkout / "scripts"
        scripts_dir.mkdir()
        (scripts_dir / "check-org-vocabulary.py").write_text("#!/usr/bin/env python3\n# Fake checker\n")
        
        # Put our actual controls file there (which contains "tenant" in policy text)
        fake_controls = ci_checkout / "controls"
        fake_controls.mkdir()
        (fake_controls / "org-vocabulary.yaml").write_text(
            REPO.joinpath("controls/org-vocabulary.yaml").read_text()
        )
        
        exit_code, output = run_checker(tmp_path)
        
        expect(exit_code == 0, f"should not fail on harness files, got {exit_code}: {output}")
        expect("[skip]" in output, f"should announce skipping harness checkout: {output}")


def test_empty_repository() -> None:
    """Test behavior on empty repository."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        
        # Create completely empty repo
        (tmp_path / "README.md").write_text("# Empty repo\n")
        
        exit_code, output = run_checker(tmp_path)
        
        expect(exit_code == 0, f"empty repo should exit 0, got {exit_code}")
        expect("no files to scan" in output or "OK" in output, 
               f"should handle empty repo gracefully: {output}")


def test_binary_files_are_skipped() -> None:
    """Test that binary files are properly skipped."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        
        # Create a fake binary file
        binary_file = tmp_path / "app.exe"
        binary_file.write_bytes(b'\x00\x01\x02\x03tenant\x04\x05\x06')
        
        # Create a text file without violations
        text_file = tmp_path / "config.yml"
        text_file.write_text("org_id: 12345\nname: test\n")
        
        exit_code, output = run_checker(tmp_path)
        
        expect(exit_code == 0, f"should skip binary files, got {exit_code}: {output}")
        expect("app.exe" not in output, f"should not mention binary file: {output}")


def test_catalog_validation() -> None:
    """Test that the catalog file is valid and self-consistent."""
    import yaml
    
    catalog_path = REPO / "controls" / "org-vocabulary.yaml"
    expect(catalog_path.exists(), "catalog file must exist")
    
    try:
        doc = yaml.safe_load(catalog_path.read_text(encoding="utf-8"))
    except yaml.YAMLError as e:
        expect(False, f"catalog must be valid YAML: {e}")
        return
    
    # Check required top-level fields
    expect("controls" in doc, "catalog must have controls section")
    expect("exceptions" in doc, "catalog must have exceptions section") 
    expect("version" in doc, "catalog must have version")
    
    # Check control structure
    controls = doc.get("controls", [])
    expect(len(controls) > 0, "must have at least one control")
    
    for control in controls:
        required_fields = ["id", "title", "owner", "scope", "status", "severity", "stage", 
                          "policy", "rationale", "remediation", "detector", "refs"]
        for field in required_fields:
            expect(field in control, f"control {control.get('id')} missing field: {field}")
    
    # Check exceptions structure  
    exceptions = doc.get("exceptions", [])
    for i, exc in enumerate(exceptions):
        expect("path" in exc, f"exception {i} must have path")
        expect("reason" in exc, f"exception {i} must have reason")


def test_case_insensitive_detection() -> None:
    """Test that tenant detection is case-insensitive."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        
        test_file = tmp_path / "test.py" 
        test_file.write_text('''TENANT_ID = "123"
Tenant = "example" 
tenant_name = "test"
getTenant = lambda: "value"
''')
        
        exit_code, output = run_checker(tmp_path)
        
        expect(exit_code == 1, f"should detect all case variations, got {exit_code}")
        # Just check that we found multiple violations, not specific strings
        expect("FAILED" in output, f"should report failures: {output}")
        expect(output.count("::error") >= 4, f"should detect all 4 variations: {output}")


def main() -> int:
    tests = [v for k, v in sorted(globals().items()) if k.startswith("test_") and callable(v)]
    for t in tests:
        try:
            t()
        except Exception as e:
            FAILURES.append(f"{t.__name__} failed with exception: {e}")
    
    if FAILURES:
        print(f"org-vocabulary self-test: FAILED ({len(FAILURES)} assertion(s))")
        for f in FAILURES:
            print(f"::error::{f}")
        return 1
    
    print(f"org-vocabulary self-test: OK ({len(tests)} test(s)) - enforcement and exception "
          f"handling validated, harness exclusion tested.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())