#!/usr/bin/env python3
"""Precision/recall and wiring tests for SP-0001..SP-0007.

Every detector is exercised against a synthetic workspace in both directions: a conformant
tree must not produce a finding, and a tree carrying exactly the defect the control names
must produce one. A control that only ever passes is indistinguishable from a control that
cannot fail, which is the failure RFC-0007 §10 records about the previous Dockerfile check.
"""

from __future__ import annotations

import importlib.util
import pathlib
import sys
import tempfile

import yaml

HERE = pathlib.Path(__file__).resolve().parent
CHECKER = HERE / "check-service-ports.py"
CONTROLS = HERE.parent / "controls" / "service-ports.yaml"
FAILURES: list[str] = []


def load_checker():
    spec = importlib.util.spec_from_file_location("check_service_ports", CHECKER)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod


m = load_checker()


def expect(condition: bool, message: str) -> None:
    if not condition:
        FAILURES.append(message)


# Two tables of identical shape, which is the point: the checker must read the CLUSTER one.
# The local values are deliberately different from the cluster ones for beta-service, so a
# detector reading the wrong table produces a visible finding rather than an accidental pass.
def registry_go(cluster: dict[str, tuple[int, int]] | None = None,
                local: dict[str, tuple[int, int]] | None = None) -> str:
    cluster = cluster if cluster is not None else {"alpha-service": (4002, 50060),
                                                  "beta-service": (4003, 50061)}
    local = local if local is not None else {"alpha-service": (4002, 50060),
                                             "beta-service": (4003, 50061)}

    # clusterListeners records membership, not a per-service port: a non-zero
    # tuple entry means that listener exists and answers on the §4.1 constant.
    def listeners(entries):
        rows = "".join(
            f'\t"{svc}": {{HTTP: {str(h != 0).lower()}, GRPC: {str(g != 0).lower()}}},\n'
            for svc, (h, g) in sorted(entries.items())
        )
        return f"var clusterListeners = map[string]listeners{{\n{rows}}}\n"

    def table(name, entries):
        rows = "".join(f'\t"{svc}": {{HTTPPort: {h}, GRPCPort: {g}}},\n'
                       for svc, (h, g) in sorted(entries.items()))
        return f"var {name} = map[string]ServiceEndpoint{{\n{rows}}}\n"

    return ("// Code generated by internal/gen/serviceports. DO NOT EDIT.\n"
            "package servicediscovery\n\n"
            + listeners(cluster) + "\n" + table("localPorts", local))


REGISTRY = registry_go()


def service_yaml(name: str, http: int, grpc: int, metrics: int, target_http: int | None = None,
                 extra: list[dict] | None = None):
    ports = [
        {"name": "http", "port": http, "targetPort": target_http or http},
        {"name": "grpc", "port": grpc, "targetPort": grpc},
        {"name": "metrics", "port": metrics, "targetPort": metrics},
    ]
    return yaml.safe_dump({
        "apiVersion": "v1", "kind": "Service",
        "metadata": {"name": f"inboxxhq-{name}"},
        "spec": {"ports": ports + (extra or [])},
    })


def deployment_yaml(ports: list[int], probe: int, env: dict[str, int] | None = None):
    container = {
        "name": "app",
        "ports": [{"containerPort": p} for p in ports],
        "livenessProbe": {"httpGet": {"path": "/health/live", "port": probe}},
        "readinessProbe": {"httpGet": {"path": "/health/ready", "port": probe}},
    }
    if env:
        container["env"] = [{"name": k, "value": str(v)} for k, v in env.items()]
    return yaml.safe_dump({
        "apiVersion": "apps/v1", "kind": "Deployment",
        "metadata": {"name": "app"},
        "spec": {"template": {"spec": {"containers": [container]}}},
    })


def monitor_yaml(name: str, port):
    return yaml.safe_dump({
        "apiVersion": "monitoring.coreos.com/v1", "kind": "ServiceMonitor",
        "metadata": {"name": f"inboxxhq-{name}-metrics"},
        "spec": {"endpoints": [{"port": port, "path": "/metrics"}]},
    })


LOCALPORTS = yaml.safe_dump({
    "version": 1,
    "services": {
        "alpha-service": {"http": 4002, "grpc": 50060, "metrics": 9102},
        "beta-service": {"http": 4003, "grpc": 50061, "metrics": 9103},
        "gamma-gateway": {"http": 4100, "grpc": 0, "metrics": 9150},
    },
})

# Routing config: resources to NAMES. No port key anywhere, which is the invariant SP-0016
# holds. The gateway is a third service so the duplicate-name control has something real to
# count, and so SP-0017 has both a Kubernetes and a local environment to judge.
GATEWAY_REGISTRY = yaml.safe_dump({
    "service_registry": {
        "version": "1.0",
        "domain_services": [
            {"name": "inboxxhq-alpha-service", "resources": ["alpha"],
             "health_path": "/health", "docs_path": "/swagger/doc.json"},
        ],
    },
})


BASE_TREE = {
    "shared/platform-shared-go/platform/servicediscovery/ports.generated.go": REGISTRY,
    "infra/inboxxhq-infra/services/alpha-service/base/service.yaml":
        service_yaml("alpha-service", 8080, 50051, 9464),
    "infra/inboxxhq-infra/services/alpha-service/base/servicemonitor.yaml":
        monitor_yaml("alpha-service", "metrics"),
    "infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
        deployment_yaml([8080, 50051, 9464], 8080, {"PORT": 8080, "PPROF_PORT": 6060}),
    "infra/inboxxhq-infra/services/beta-service/base/service.yaml":
        service_yaml("beta-service", 8080, 50051, 9464),
    "infra/inboxxhq-infra/services/beta-service/base/servicemonitor.yaml":
        monitor_yaml("beta-service", "metrics"),
    "infra/inboxxhq-infra/services/beta-service/overlays/dev/deployment.yaml":
        deployment_yaml([8080, 50051, 9464], 8080, {"PORT": 8080}),
    "services/alpha/inboxxhq-alpha-service/service.contract.yaml":
        "service:\n  name: alpha-service\n  ports:\n    http: 8080\n    grpc: 50051\n",
    "services/alpha/inboxxhq-alpha-service/Dockerfile":
        "FROM alpine:3.24\nEXPOSE 8080 50051 9464\n"
        "HEALTHCHECK CMD wget -q http://localhost:8080/health/live\nCMD [\"/app/alpha\"]\n",
    "services/beta/inboxxhq-beta-service/service.contract.yaml":
        "name: beta-service\nports:\n  http: 8080\n  grpc: 50051\n",
    "services/beta/inboxxhq-beta-service/Dockerfile":
        "FROM alpine:3.24\nEXPOSE 8080\n"
        "HEALTHCHECK CMD wget -q http://localhost:8080/health/live\nCMD [\"/app/beta\"]\n",
    # The SOURCE of the §4.2 local allocation. The values are deliberately NOT the §4.1
    # constants: a fixture whose "local" ports were 8080/50051 would make SP-0013 pass by
    # agreeing with the defect it exists to catch.
    "shared/platform-shared-go/platform/servicediscovery/localports.yaml": LOCALPORTS,
    "services/alpha/inboxxhq-alpha-service/env.example":
        "ENVIRONMENT=local\nPORT=4002\nGRPC_PORT=50060\nMETRICS_PORT=9102\n",
    "gateways/inboxxhq-gamma-gateway/config/base/service-registry.yaml":
        GATEWAY_REGISTRY,
    "gateways/inboxxhq-gamma-gateway/config/environments/prod.yaml":
        "environment: prod\nserver:\n  port: 8080\n  host: \"0.0.0.0\"\n",
    "gateways/inboxxhq-gamma-gateway/config/environments/local.yaml":
        "environment: local\nserver:\n  port: 4100\n  host: \"0.0.0.0\"\n",
}


# Held for the process lifetime on purpose. Several detectors read files at DETECTION time
# rather than at Workspace construction, so a tree removed when a context manager exits is a
# tree they see as empty - and an empty tree is INDETERMINATE, which reads as "no finding".
# The first draft of this file did exactly that and reported nine passing controls that had
# never been given anything to look at.
_TREES: list[tempfile.TemporaryDirectory] = []


def run(overrides: dict[str, str] | None = None, drop: tuple[str, ...] = ()):
    holder = tempfile.TemporaryDirectory()
    _TREES.append(holder)
    root = pathlib.Path(holder.name)
    tree = dict(BASE_TREE)
    for key in drop:
        tree.pop(key, None)
    tree.update(overrides or {})
    for rel, text in tree.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return m.Workspace(root)


# --- conformant baseline ------------------------------------------------------------------

ws = run()
expect(len(ws.services) == 2, f"conformant: expected 2 services, got {len(ws.services)}")
expect(len(ws.registry) == 2, f"conformant: expected 2 registry entries, got {len(ws.registry)}")
expect(len(ws.repos_by_service) == 3,
       f"conformant: expected 3 repos (two services and a gateway), got "
       f"{sorted(ws.repos_by_service)}")

for name, detector in (
    ("SP-0001", m.k8s_ports_internally_consistent),
    ("SP-0002", m.k8s_ports_match_registry),
    ("SP-0003", m.no_reserved_ports),
    ("SP-0004", m.dockerfile_ports_are_own),
    ("SP-0005", m.contract_ports_match_service),
    ("SP-0007", m.manifest_address_vars),
    ("SP-0008", m.pprof_is_the_constant_and_stays_private),
    ("SP-0009", m.local_allocation_is_per_service),
    ("SP-0010", m.metrics_are_scraped_by_port_name),
    ("SP-0013", m.local_allocation_source_is_valid),
    ("SP-0014", m.env_example_matches_local_allocation),
    ("SP-0015", m.contracts_hold_no_foreign_ports),
    ("SP-0016", m.routing_config_holds_no_ports),
    ("SP-0017", m.gateway_bind_port_is_right_for_its_environment),
    ("SP-0018", m.one_repository_per_service),
    ("SP-0019", m.service_repos_hold_no_manifests),
):
    finding = detector(ws)
    expect(finding.count == 0 and not finding.indeterminate,
           f"{name}: conformant tree produced {finding.count} finding(s): {finding.evidence}")

# SP-0006 is enforced: the fixture is on the §4.1 constants, which is the fleet's
# actual state. A pass here is the control holding, not the control going inert.
expect(m.k8s_ports_are_constants(ws).count == 0 and not m.k8s_ports_are_constants(ws).indeterminate,
       f"SP-0006: expected the fixture to be on the constants; got {m.k8s_ports_are_constants(ws)}")


# --- SP-0001: the §11 atomicity invariant --------------------------------------------------

ws = run({"infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
          deployment_yaml([8080, 50051, 9464], 9999, {"PORT": 8080})})
finding = m.k8s_ports_internally_consistent(ws)
expect(finding.count == 1 and "probe targets 9999" in " ".join(finding.details),
       f"SP-0001: a probe on an unbound port must be caught; got {finding.details}")

ws = run({"infra/inboxxhq-infra/services/alpha-service/base/service.yaml":
          service_yaml("alpha-service", 8080, 50051, 9464, target_http=4002)})
finding = m.k8s_ports_internally_consistent(ws)
expect(any("targetPort=4002" in d for d in finding.details),
       f"SP-0001: port != targetPort must be caught; got {finding.details}")

ws = run({"infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
          deployment_yaml([4002, 50051, 9464], 4002, {"PORT": 4002})})
finding = m.k8s_ports_internally_consistent(ws)
expect(finding.count >= 1 and any("containerPort 4002" in d for d in finding.details),
       f"SP-0001: a half-migrated service must be caught; got {finding.details}")

ws = run({"infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
          deployment_yaml([8080, 50051, 9464], 8080, {"PORT": 4002})})
expect(any("PORT=4002" in d for d in m.k8s_ports_internally_consistent(ws).details),
       "SP-0001: a PORT env value no container binds must be caught")

# Membership in the containerPort set is not enough. PORT=50051 on a service publishing
# http=8080 is a member of the set and still wrong: the HTTP listener is being advertised on
# the gRPC number, which is the exact confusion a migration under time pressure produces.
ws = run({"infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
          deployment_yaml([8080, 50051, 9464], 8080, {"PORT": 50051})})
finding = m.k8s_ports_internally_consistent(ws)
expect(any("publishes http=8080" in d for d in finding.details),
       f"SP-0001: PORT naming another concern's port must be caught; got {finding.details}")

ws = run({"infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
          deployment_yaml([8080, 50051, 9464], 8080,
                          {"PORT": 8080, "METRICS_PORT": 50051})})
expect(any("publishes metrics=9464" in d
           for d in m.k8s_ports_internally_consistent(ws).details),
       "SP-0001: METRICS_PORT naming the gRPC port must be caught")


# --- SP-0002: registry agreement ------------------------------------------------------------

ws = run({"infra/inboxxhq-infra/services/alpha-service/base/service.yaml":
          service_yaml("alpha-service", 4002, 50051, 9464),
          "infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
          deployment_yaml([4002, 50051, 9464], 4002, {"PORT": 4002})})
finding = m.k8s_ports_match_registry(ws)
expect(finding.count == 1 and "resolves callers to 8080" in " ".join(finding.details),
       f"SP-0002: manifest behind the registry must be caught; got {finding.details}")

ws = run(drop=("shared/platform-shared-go/platform/servicediscovery/ports.generated.go",))
expect(m.k8s_ports_match_registry(ws).indeterminate,
       "SP-0002: an absent registry must be INDETERMINATE, never a pass")

# A component with no registry entry is scrape-only infrastructure, not a violation.
ws = run({"infra/inboxxhq-infra/services/kafka-exporter/base/service.yaml":
          service_yaml("kafka-exporter", 9308, 9309, 9310)})
finding = m.k8s_ports_match_registry(ws)
expect(finding.count == 0 and any("kafka-exporter" in d for d in finding.details),
       f"SP-0002: an unregistered component must be reported, not counted; got {finding}")

# Zero in the registry means "no listener of this kind", and the callers refuse rather than
# dial it. A Service that publishes the port anyway is reachable by everything except the one
# path RFC-0007 §5 allows, and that used to pass because the comparison skipped a falsy value.
ws = run({"shared/platform-shared-go/platform/servicediscovery/ports.generated.go":
          registry_go(cluster={"alpha-service": (4002, 0), "beta-service": (4003, 50061)})})
finding = m.k8s_ports_match_registry(ws)
expect(finding.count == 1 and "records no grpc port" in " ".join(finding.details),
       f"SP-0002: a published port the registry cannot resolve must be caught; got {finding.details}")

# THE TABLE-CONFUSION HAZARD, and the reason this file has a two-table fixture at all.
#
# ports.generated.go holds clusterPorts and localPorts in the same shape. A detector matching
# entries anywhere in the file collects both, and the last write wins -- so SP-0002 would
# compare the manifests against the LOCAL table. That is green while a service is unmigrated
# and the two tables agree, and it goes red the moment one migrates, with a finding shaped
# exactly like the outage SP-0002 exists to catch. Here the local table alone carries the old
# numbers and the manifests and cluster table are both migrated, so reading the wrong one is
# the only way to produce a finding.
ws = run({"shared/platform-shared-go/platform/servicediscovery/ports.generated.go":
          registry_go(cluster={"alpha-service": (8080, 50051), "beta-service": (4003, 50061)},
                      local={"alpha-service": (4002, 50060), "beta-service": (4003, 50061)}),
          "infra/inboxxhq-infra/services/alpha-service/base/service.yaml":
          service_yaml("alpha-service", 8080, 50051, 9464),
          "infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
          deployment_yaml([8080, 50051, 9464], 8080, {"PORT": 8080})})
expect(ws.registry["alpha-service"] == (8080, 50051),
       f"SP-0002: the CLUSTER table must be the one parsed; got {ws.registry.get('alpha-service')}")
expect(ws.local_registry["alpha-service"] == (4002, 50060),
       f"SP-0002: the local table must be read separately; got {ws.local_registry.get('alpha-service')}")
finding = m.k8s_ports_match_registry(ws)
expect(finding.count == 0,
       f"SP-0002: a migrated service must agree with the cluster table, not the local one; "
       f"got {finding.details}")

# The pre-split file, whose single table served both environments. It must be INDETERMINATE and
# say why -- parsing it as the cluster table is what would silently resolve callers to a
# workstation's port.
ws = run({"shared/platform-shared-go/platform/servicediscovery/ports.generated.go":
          '// Code generated by internal/gen/serviceports. DO NOT EDIT.\n'
          'package servicediscovery\n\n'
          'var standardPorts = map[string]ServiceEndpoint{\n'
          '\t"alpha-service": {HTTPPort: 4002, GRPCPort: 50060},\n}\n'})
finding = m.k8s_ports_match_registry(ws)
expect(finding.indeterminate and "standardPorts" in finding.evidence,
       f"SP-0002: a pre-split registry must be INDETERMINATE and name the old table; got {finding.evidence}")


# --- SP-0003: reserved ports ----------------------------------------------------------------

ws = run({"infra/inboxxhq-infra/services/alpha-service/base/service.yaml":
          service_yaml("alpha-service", 9090, 50060, 9102)})
expect(m.no_reserved_ports(ws).count >= 1,
       "SP-0003: publishing Prometheus's 9090 must be caught")

ws = run({"infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
          deployment_yaml([8080, 50051, 5432], 8080, {"PORT": 8080})})
expect(m.no_reserved_ports(ws).count >= 1,
       "SP-0003: binding PostgreSQL's 5432 as a containerPort must be caught")


# --- SP-0004: a Dockerfile names only its own ports -----------------------------------------

ws = run({"services/alpha/inboxxhq-alpha-service/Dockerfile":
          "FROM alpine:3.24\nEXPOSE 4003\n"
          "HEALTHCHECK CMD wget -q http://localhost:4003/health/live\nCMD [\"/app/alpha\"]\n"})
finding = m.dockerfile_ports_are_own(ws)
expect(finding.count >= 1 and "does not publish" in " ".join(finding.details),
       f"SP-0004: exposing a port the service does not publish must be caught; got {finding.details}")

ws = run({"services/alpha/inboxxhq-alpha-service/Dockerfile":
          "FROM alpine:3.24\nEXPOSE 4002\n"
          "HEALTHCHECK CMD wget -q http://localhost:9999/health/live\nCMD [\"/app/alpha\"]\n"})
expect(m.dockerfile_ports_are_own(ws).count >= 1,
       "SP-0004: a HEALTHCHECK on a port the service does not publish must be caught")

# The identity rule that makes SP-0004 usable: a repository directory name is not a service
# name. inboxxhq-notification-service-ctx holds notification-service, and reading the
# directory instead of the contract turns a correct repository into a false finding.
ws = run({"services/alpha/inboxxhq-alpha-service-ctx/service.contract.yaml":
          "service:\n  name: alpha-service\n  ports:\n    http: 4002\n",
          "services/alpha/inboxxhq-alpha-service-ctx/Dockerfile":
          "FROM alpine:3.24\nEXPOSE 4002\n"
          "HEALTHCHECK CMD wget -q http://localhost:4002/health/live\nCMD [\"/app/a\"]\n"})
expect(m.dockerfile_ports_are_own(ws).count == 0,
       "SP-0004: a variant repo declaring its real service name must not be a finding")


# --- SP-0005: contract agreement ------------------------------------------------------------

ws = run({"services/alpha/inboxxhq-alpha-service/service.contract.yaml":
          "service:\n  name: alpha-service\n  ports:\n    http: 4031\n    grpc: 50060\n"})
finding = m.contract_ports_match_service(ws)
expect(finding.count >= 1 and "publishes 8080" in " ".join(finding.details),
       f"SP-0005: a contract disagreeing with the manifest must be caught; got {finding.details}")

ws = run({"services/beta/inboxxhq-beta-service/service.contract.yaml":
          "name: beta-service\nports:\n  http: 4003\n  grpc: 50061\n  websocket: 4002\n"})
finding = m.contract_ports_match_service(ws)
expect(finding.count >= 1,
       f"SP-0005: a contract claiming a port the Service does not publish must be caught; got {finding.details}")

ws = run({"docs/core-docs/catalog/services/alpha-service.yaml":
          "name: alpha-service\ncanonical_port: 4031\n"})
finding = m.contract_ports_match_service(ws)
expect(finding.count == 1 and "canonical_port=4031" in " ".join(finding.details),
       f"SP-0005: a drifted catalog canonical_port must be caught; got {finding.details}")

ws = run({"docs/core-docs/catalog/services/alpha-service.yaml":
          "name: alpha-service\ncanonical_port: 8080\n"})
finding = m.contract_ports_match_service(ws)
expect(finding.count == 0 and "canonical_port(s) agree" in finding.evidence,
       f"SP-0005: an agreeing canonical_port must be credited in the evidence; got {finding}")

ws = run()
expect("catalog was not in the workspace" in m.contract_ports_match_service(ws).evidence,
       "SP-0005: an absent catalog must be stated, not silently treated as agreement")

# Both live contract shapes must be read. The top-level form is beta's; if only one shape
# parsed, half the fleet would be silently skipped and the control would report clean.
ws = run()
declared, _ = m._contract_ports(ws.root / "services/beta/inboxxhq-beta-service")
expect(declared == {"http": 8080, "grpc": 50051},
       f"SP-0005: top-level `ports:` contract shape must parse; got {declared}")
declared, _ = m._contract_ports(ws.root / "services/alpha/inboxxhq-alpha-service")
expect(declared == {"http": 8080, "grpc": 50051},
       f"SP-0005: nested `service.ports:` contract shape must parse; got {declared}")


# --- SP-0006: the constants, per concern -----------------------------------------------------

# Three of the four numbers right is not migrated, and the set test said it was: every port
# below is one of the §4.1 constants, and http=9464 serves an API where callers expect one and
# scrapers expect metrics.
ws = run({"infra/inboxxhq-infra/services/alpha-service/base/service.yaml":
          service_yaml("alpha-service", 9464, 50051, 8080),
          "infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
          deployment_yaml([9464, 50051, 8080], 9464, {"PORT": 9464})})
finding = m.k8s_ports_are_constants(ws)
expect(any("publishes http=9464, not 8080" in d for d in finding.details),
       f"SP-0006: constants assigned to the wrong concern must be caught; got {finding.details}")

# A Service on the constants whose overlay still binds the old number is the half-migrated
# state RFC-0007 §11 says takes a service down. SP-0006 must not count it as migrated.
ws = run({"infra/inboxxhq-infra/services/alpha-service/base/service.yaml":
          service_yaml("alpha-service", 8080, 50051, 9464),
          "infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
          deployment_yaml([4002, 50060, 9102], 4002, {"PORT": 4002})})
finding = m.k8s_ports_are_constants(ws)
expect(any("dev binds containerPort 4002" in d for d in finding.details),
       f"SP-0006: an overlay left behind must be reported; got {finding.details}")

ws = run({"shared/platform-shared-go/platform/servicediscovery/ports.generated.go":
          registry_go(cluster={"alpha-service": (8080, 50051), "beta-service": (8080, 50051)},
                      local={"alpha-service": (4002, 50060), "beta-service": (4003, 50061)}),
          "infra/inboxxhq-infra/services/alpha-service/base/service.yaml":
          service_yaml("alpha-service", 8080, 50051, 9464),
          "infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
          deployment_yaml([8080, 50051, 9464], 8080, {"PORT": 8080, "PPROF_PORT": 6060}),
          "infra/inboxxhq-infra/services/beta-service/base/service.yaml":
          service_yaml("beta-service", 8080, 50051, 9464),
          "infra/inboxxhq-infra/services/beta-service/overlays/dev/deployment.yaml":
          deployment_yaml([8080, 50051, 9464], 8080, {"PORT": 8080})})
finding = m.k8s_ports_are_constants(ws)
expect(finding.count == 0, f"SP-0006: a fully migrated fleet must produce no finding; got "
                           f"{finding.details}")
# ...and every other control has to stay green on it, because that is the state Phase 4 flips
# SP-0006 to active in. A control that only passes on the pre-migration fleet is a control
# that blocks the migration finishing.
for name, detector in (("SP-0001", m.k8s_ports_internally_consistent),
                       ("SP-0002", m.k8s_ports_match_registry),
                       ("SP-0003", m.no_reserved_ports),
                       ("SP-0008", m.pprof_is_the_constant_and_stays_private),
                       ("SP-0009", m.local_allocation_is_per_service),
                       ("SP-0010", m.metrics_are_scraped_by_port_name)):
    f = detector(ws)
    expect(f.count == 0 and not f.indeterminate,
           f"{name}: must hold on a fully migrated fleet; got {f.count} - {f.evidence}")


# --- SP-0008: pprof, the fourth listener ------------------------------------------------------

ws = run({"infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
          deployment_yaml([4002, 50060, 9102], 4002, {"PORT": 4002, "PPROF_PORT": 6095})})
finding = m.pprof_is_the_constant_and_stays_private(ws)
expect(finding.count == 1 and "PPROF_PORT=6095" in " ".join(finding.details),
       f"SP-0008: a PPROF_PORT that is not 6060 must be caught; got {finding.details}")

# The half that matters more: pprof with a containerPort is a heap-dump surface reachable from
# anywhere in the cluster, which RFC-0007 §9 forbids by requiring it to bind 127.0.0.1.
ws = run({"infra/inboxxhq-infra/services/alpha-service/base/service.yaml":
          service_yaml("alpha-service", 4002, 50060, 9102),
          "infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
          deployment_yaml([4002, 50060, 9102, 6060], 4002, {"PORT": 4002})})
expect(any("exposes pprof to the cluster" in d
           for d in m.pprof_is_the_constant_and_stays_private(ws).details),
       "SP-0008: a containerPort for pprof must be caught")

ws = run({"infra/inboxxhq-infra/services/alpha-service/base/service.yaml":
          service_yaml("alpha-service", 4002, 50060, 9102,
                       extra=[{"name": "pprof", "port": 6060, "targetPort": 6060}])})
expect(any("keeps pprof on 127.0.0.1" in d
           for d in m.pprof_is_the_constant_and_stays_private(ws).details),
       "SP-0008: a Service publishing pprof must be caught")


# --- SP-0009: the local carve-out stays a carve-out --------------------------------------------

ws = run({"shared/platform-shared-go/platform/servicediscovery/ports.generated.go":
          registry_go(local={"alpha-service": (4002, 50060)})})
finding = m.local_allocation_is_per_service(ws)
expect(finding.count == 1 and "beta-service" in " ".join(finding.details),
       f"SP-0009: a service with no local allocation must be caught; got {finding.details}")

# The regression this control exists for: regenerating the local table from the manifests
# again. The manifests converge on one number, so the local table becomes a collision the
# moment two services have migrated -- which is the bind failure RFC-0007 §4.2 prevents.
ws = run({"shared/platform-shared-go/platform/servicediscovery/ports.generated.go":
          registry_go(cluster={"alpha-service": (8080, 50051), "beta-service": (8080, 50051)},
                      local={"alpha-service": (8080, 50051), "beta-service": (8080, 50051)})})
finding = m.local_allocation_is_per_service(ws)
expect(finding.count >= 2 and "cannot bind it" in " ".join(finding.details),
       f"SP-0009: a local table flattened onto the constants must be caught; got {finding.details}")

ws = run(drop=("shared/platform-shared-go/platform/servicediscovery/ports.generated.go",))
expect(m.local_allocation_is_per_service(ws).indeterminate,
       "SP-0009: an absent registry must be INDETERMINATE, never a pass")


# --- SP-0010: metrics are scraped by name ------------------------------------------------------

ws = run({"infra/inboxxhq-infra/services/alpha-service/base/servicemonitor.yaml":
          monitor_yaml("alpha-service", 9102)})
finding = m.metrics_are_scraped_by_port_name(ws)
expect(finding.count == 1 and "scrapes port 9102 by number" in " ".join(finding.details),
       f"SP-0010: a numeric ServiceMonitor port must be caught; got {finding.details}")

ws = run(drop=("infra/inboxxhq-infra/services/alpha-service/base/servicemonitor.yaml",
               "infra/inboxxhq-infra/services/beta-service/base/servicemonitor.yaml"))
expect(m.metrics_are_scraped_by_port_name(ws).indeterminate,
       "SP-0010: no ServiceMonitor at all must be INDETERMINATE, not a pass over nothing")


# --- SP-0007: advisory address-variable cross-check ------------------------------------------

ws = run({"infra/inboxxhq-infra/services/alpha-service/overlays/dev/configmap-patch.yaml":
          "data:\n  x: y\nenv:\n  - name: BETA_SERVICE_URL\n    value: http://beta:4003\n"})
expect(m.manifest_address_vars(ws).count == 1,
       "SP-0007: a manifest address variable must be counted")

ws = run({"infra/inboxxhq-infra/services/alpha-service/overlays/dev/configmap-patch.yaml":
          "env:\n  - name: KUBERNETES_SERVICE_HOST\n    value: x\n"
          "  - name: BETA_USE_GRPC\n    value: 'true'\n"
          "  - name: CHECKOUT_SUCCESS_URL\n    value: https://example.test\n"})
expect(m.manifest_address_vars(ws).count == 0,
       "SP-0007: transport toggles, the Kubernetes API host and external URLs are not addresses")


# --- SP-0013..SP-0019: the defects found on 2026-08-30 ---------------------------------------
#
# Each fixture below is the real defect, reduced. A control whose test invents a defect nobody
# ever committed proves the detector runs; these prove it catches the thing that got through.

# SP-0013: demo-service sat in the allocation as the CLUSTER constants, captured by
# regenerating the local table from manifests that had already migrated.
ws = run({"shared/platform-shared-go/platform/servicediscovery/localports.yaml":
          yaml.safe_dump({"version": 1, "services": {
              "alpha-service": {"http": 8080, "grpc": 50051, "metrics": 9464},
              "beta-service": {"http": 4003, "grpc": 50061, "metrics": 9103},
              "gamma-gateway": {"http": 4100, "grpc": 0, "metrics": 9150}}})})
finding = m.local_allocation_source_is_valid(ws)
expect(finding.count >= 1 and "CLUSTER constant" in " ".join(finding.details),
       f"SP-0013: a local allocation holding the §4.1 constants must be caught; got {finding.details}")

# SP-0013: two services sharing a local port -- the collision §4.2 exists to prevent.
ws = run({"shared/platform-shared-go/platform/servicediscovery/localports.yaml":
          yaml.safe_dump({"version": 1, "services": {
              "alpha-service": {"http": 4002, "grpc": 50060, "metrics": 9102},
              "beta-service": {"http": 4003, "grpc": 50061, "metrics": 9102},
              "gamma-gateway": {"http": 4100, "grpc": 0, "metrics": 9150}}})})
finding = m.local_allocation_source_is_valid(ws)
expect(finding.count >= 1 and "already held by" in " ".join(finding.details),
       f"SP-0013: a duplicate local port must be caught; got {finding.details}")

# SP-0013: a zero means "no listener", not a collision, however many services have one.
ws = run({"shared/platform-shared-go/platform/servicediscovery/localports.yaml":
          yaml.safe_dump({"version": 1, "services": {
              "alpha-service": {"http": 4002, "grpc": 0, "metrics": 9102},
              "beta-service": {"http": 4003, "grpc": 0, "metrics": 9103},
              "gamma-gateway": {"http": 4100, "grpc": 0, "metrics": 9150}}}),
          "shared/platform-shared-go/platform/servicediscovery/ports.generated.go":
          registry_go(local={"alpha-service": (4002, 0), "beta-service": (4003, 0)})})
finding = m.local_allocation_source_is_valid(ws)
expect(finding.count == 0,
       f"SP-0013: 0 marks an absent listener and must never count as a collision; "
       f"got {finding.details}")

# SP-0014: dashboard-service's env.example carried the cluster constants.
ws = run({"services/alpha/inboxxhq-alpha-service/env.example":
          "ENVIRONMENT=local\nPORT=8080\nGRPC_PORT=50051\nMETRICS_PORT=9464\n"})
finding = m.env_example_matches_local_allocation(ws)
expect(finding.count == 3 and "CLUSTER constant" in " ".join(finding.details),
       f"SP-0014: env.example on the constants must be caught, and named as such; got {finding.details}")

# SP-0015: call-routing-service listed its upstreams' gRPC ports, two schemes out of date.
ws = run({"services/alpha/inboxxhq-alpha-service/service.contract.yaml":
          "service:\n  name: alpha-service\nports:\n  http: 8080\n  grpc: 50051\n"
          "dependencies:\n  services:\n    - name: beta-service\n      type: grpc\n"
          "      port: 50011\n"})
finding = m.contracts_hold_no_foreign_ports(ws)
expect(finding.count == 1 and "upstream" in " ".join(finding.details),
       f"SP-0015: an upstream port in a contract must be caught; got {finding.details}")

# SP-0015: ...and the same file's second answer about its own metrics port.
ws = run({"services/alpha/inboxxhq-alpha-service/service.contract.yaml":
          "service:\n  name: alpha-service\nports:\n  http: 8080\n  grpc: 50051\n"
          "  metrics: 9464\nobservability:\n  metrics:\n    port: 9121\n"
          "    path: /metrics\n"})
finding = m.contracts_hold_no_foreign_ports(ws)
expect(finding.count == 1 and "second answer" in " ".join(finding.details),
       f"SP-0015: a contradicting metrics port must be caught; got {finding.details}")

# SP-0016: edge-gateway's routing config held 99 keys of the withdrawn allocation.
ws = run({"gateways/inboxxhq-gamma-gateway/config/base/service-registry.yaml":
          yaml.safe_dump({"service_registry": {"domain_services": [
              {"name": "inboxxhq-alpha-service", "port": 4002, "grpc_port": 50060,
               "resources": ["alpha"]}]}})})
finding = m.routing_config_holds_no_ports(ws)
expect(finding.count == 2, f"SP-0016: both port keys must be caught; got {finding.details}")

# SP-0017: prod committed `server.port: 80`, the ingress's own reserved port.
ws = run({"gateways/inboxxhq-gamma-gateway/config/environments/prod.yaml":
          "environment: prod\nserver:\n  port: 80\n"})
finding = m.gateway_bind_port_is_right_for_its_environment(ws)
expect(finding.count == 1 and "RESERVED" in " ".join(finding.details),
       f"SP-0017: a reserved bind port must be caught and named reserved; got {finding.details}")

# SP-0017: dev committed 4000 -- a per-service number in a Kubernetes environment.
ws = run({"gateways/inboxxhq-gamma-gateway/config/environments/dev.yaml":
          "environment: dev\nserver:\n  port: 4100\n"})
finding = m.gateway_bind_port_is_right_for_its_environment(ws)
expect(finding.count == 1 and "8080" in " ".join(finding.details),
       f"SP-0017: a per-service port in a cluster environment must be caught; got {finding.details}")

# SP-0017: local is NOT a fifth cluster. A workstation on its own port is correct, and a
# control that fails it here is the §12.1 over-correction rebuilt in CI.
ws = run()
expect(m.gateway_bind_port_is_right_for_its_environment(ws).count == 0,
       "SP-0017: local.yaml on the §4.2 port must pass; treating it as a cluster is the "
       "over-correction §12.1 records")
ws = run({"gateways/inboxxhq-gamma-gateway/config/environments/local.yaml":
          "environment: local\nserver:\n  port: 4999\n"})
expect(m.gateway_bind_port_is_right_for_its_environment(ws).count == 1,
       "SP-0017: local.yaml disagreeing with the allocation must still be caught")

# SP-0018: a stale second checkout claiming the same service name takes its own Dockerfile
# out of SP-0004 -- exempt from the check precisely because it is stale.
ws = run({"services/alpha/inboxxhq-alpha-service-ctx/service.contract.yaml":
          "service:\n  name: alpha-service\n  ports:\n    http: 8080\n",
          "services/alpha/inboxxhq-alpha-service-ctx/Dockerfile":
          "FROM alpine:3.24\nEXPOSE 4009\n"})
expect(m.dockerfile_ports_are_own(ws).count == 0,
       "SP-0018 premise: the stale copy's Dockerfile is invisible to SP-0004, which is why "
       "SP-0018 has to exist")
finding = m.one_repository_per_service(ws)
expect(finding.count == 1 and "alpha-service" in " ".join(finding.details),
       f"SP-0018: two directories claiming one service name must be caught; got {finding.details}")

# SP-0019: observability-service carried its own manifests, on pre-migration ports.
ws = run({"services/alpha/inboxxhq-alpha-service/k8s/base/service.yaml":
          service_yaml("alpha-service", 4032, 50092, 9133)})
finding = m.service_repos_hold_no_manifests(ws)
expect(finding.count == 1 and "4032" in " ".join(finding.details),
       f"SP-0019: in-repo manifests must be caught, with their stale ports named; got {finding.details}")

# SP-0013/SP-0014 must be honestly INDETERMINATE without a source, never a silent pass.
ws = run(drop=("shared/platform-shared-go/platform/servicediscovery/localports.yaml",))
expect(m.local_allocation_source_is_valid(ws).count == 1,
       "SP-0013: a missing allocation source is a finding, not a pass")
expect(m.env_example_matches_local_allocation(ws).indeterminate,
       "SP-0014: without the allocation source the control must report indeterminate")


# --- catalog wiring ---------------------------------------------------------------------------

catalog = yaml.safe_load(CONTROLS.read_text(encoding="utf-8"))
ids = [c["id"] for c in catalog["controls"]]
expect(len(ids) == len(set(ids)), "catalog: duplicate control id")
for control in catalog["controls"]:
    expect(control["detector"] in m.DETECTORS,
           f"catalog: {control['id']} names unknown detector {control['detector']!r}")
    for field in m.REQUIRED_FIELDS:
        expect(bool(control.get(field)), f"catalog: {control['id']} missing {field}")
    expect(control["status"] in m.VALID_STATUS,
           f"catalog: {control['id']} has invalid status {control['status']!r}")
expect(sum(1 for c in catalog["controls"] if c["status"] == "deferred") == 0,
       "catalog: SP-0006 is enforced; no control should be deferred")

# SP-0006 is active. A conformant (migrated) tree must pass it, and it must be
# enforced, or a service moving back off the constants would be decorative.
ws = run()
results = m.evaluate(ws, catalog["controls"], {})
sp6 = [r for r in results if r["control"] == "SP-0006"]
expect(sp6 and sp6[0]["result"] == "pass",
       f"wiring: SP-0006 must evaluate to 'pass' on the constants fixture; got {sp6}")

report = m.build_report(ws, results, catalog, "major", m.SEVERITY_ORDER["major"])
expect(report["deferred"] == 0, f"wiring: report should count 0 deferred; got {report}")
expect(report["ok"],
       f"wiring: a conformant migrated tree must pass; got {report['enforced_failures']} "
       f"enforced failure(s)")

# ...and an unbaselined finding must still fail it, or the whole lane is decorative.
dirty = run({"services/alpha/inboxxhq-alpha-service/service.contract.yaml":
             "service:\n  name: alpha-service\n  ports:\n    http: 4031\n"})
dirty_report = m.build_report(dirty, m.evaluate(dirty, catalog["controls"], {}), catalog,
                              "major", m.SEVERITY_ORDER["major"])
expect(not dirty_report["ok"],
       "wiring: an unbaselined SP-0005 finding must fail the report")

# The ratchet: the same finding, frozen, passes; and one MORE than the baseline fails.
frozen = m.build_report(dirty, m.evaluate(dirty, catalog["controls"], {"SP-0005": 1}),
                        catalog, "major", m.SEVERITY_ORDER["major"])
expect(frozen["ok"], "wiring: a frozen finding must not fail the gate")
tightened = m.evaluate(dirty, catalog["controls"], {"SP-0005": 0})
expect(any(r["control"] == "SP-0005" and r["result"] == "fail" for r in tightened),
       "wiring: a count above the baseline must fail")
loosened = m.evaluate(run(), catalog["controls"], {"SP-0005": 3})
expect(any(r["control"] == "SP-0005" and r["result"] == "improved" for r in loosened),
       "wiring: a count below the baseline must report as improved")


if FAILURES:
    print(f"service-ports tests: {len(FAILURES)} FAILURE(S)")
    for failure in FAILURES:
        print(f"  - {failure}")
    raise SystemExit(1)
print("service-ports tests: all assertions passed")
