#!/usr/bin/env python3
"""Precision/recall and wiring tests for SP-0001..SP-0007.

Every detector is exercised against a synthetic workspace in both directions: a conformant
tree must not produce a finding, and a tree carrying exactly the defect the control names
must produce one. A control that only ever passes is indistinguishable from a control that
cannot fail, which is the failure RFC-0007 §10 records about the previous Dockerfile check.
"""

from __future__ import annotations

import importlib.util
import pathlib
import sys
import tempfile

import yaml

HERE = pathlib.Path(__file__).resolve().parent
CHECKER = HERE / "check-service-ports.py"
CONTROLS = HERE.parent / "controls" / "service-ports.yaml"
FAILURES: list[str] = []


def load_checker():
    spec = importlib.util.spec_from_file_location("check_service_ports", CHECKER)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod


m = load_checker()


def expect(condition: bool, message: str) -> None:
    if not condition:
        FAILURES.append(message)


REGISTRY = '''// Code generated by internal/gen/serviceports. DO NOT EDIT.
package servicediscovery

var standardPorts = map[string]ServiceEndpoint{
\t"alpha-service": {HTTPPort: 4002, GRPCPort: 50060},
\t"beta-service":  {HTTPPort: 4003, GRPCPort: 50061},
}
'''


def service_yaml(name: str, http: int, grpc: int, metrics: int, target_http: int | None = None):
    return yaml.safe_dump({
        "apiVersion": "v1", "kind": "Service",
        "metadata": {"name": f"inboxxhq-{name}"},
        "spec": {"ports": [
            {"name": "http", "port": http, "targetPort": target_http or http},
            {"name": "grpc", "port": grpc, "targetPort": grpc},
            {"name": "metrics", "port": metrics, "targetPort": metrics},
        ]},
    })


def deployment_yaml(ports: list[int], probe: int, env: dict[str, int] | None = None):
    container = {
        "name": "app",
        "ports": [{"containerPort": p} for p in ports],
        "livenessProbe": {"httpGet": {"path": "/health/live", "port": probe}},
        "readinessProbe": {"httpGet": {"path": "/health/ready", "port": probe}},
    }
    if env:
        container["env"] = [{"name": k, "value": str(v)} for k, v in env.items()]
    return yaml.safe_dump({
        "apiVersion": "apps/v1", "kind": "Deployment",
        "metadata": {"name": "app"},
        "spec": {"template": {"spec": {"containers": [container]}}},
    })


BASE_TREE = {
    "shared/platform-shared-go/platform/servicediscovery/ports.generated.go": REGISTRY,
    "infra/inboxxhq-infra/services/alpha-service/base/service.yaml":
        service_yaml("alpha-service", 4002, 50060, 9102),
    "infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
        deployment_yaml([4002, 50060, 9102], 4002, {"PORT": 4002}),
    "infra/inboxxhq-infra/services/beta-service/base/service.yaml":
        service_yaml("beta-service", 4003, 50061, 9103),
    "infra/inboxxhq-infra/services/beta-service/overlays/dev/deployment.yaml":
        deployment_yaml([4003, 50061, 9103], 4003, {"PORT": 4003}),
    "services/alpha/inboxxhq-alpha-service/service.contract.yaml":
        "service:\n  name: alpha-service\n  ports:\n    http: 4002\n    grpc: 50060\n",
    "services/alpha/inboxxhq-alpha-service/Dockerfile":
        "FROM alpine:3.24\nEXPOSE 4002 50060 9102\n"
        "HEALTHCHECK CMD wget -q http://localhost:4002/health/live\nCMD [\"/app/alpha\"]\n",
    "services/beta/inboxxhq-beta-service/service.contract.yaml":
        "name: beta-service\nports:\n  http: 4003\n  grpc: 50061\n",
    "services/beta/inboxxhq-beta-service/Dockerfile":
        "FROM alpine:3.24\nEXPOSE 4003\n"
        "HEALTHCHECK CMD wget -q http://localhost:4003/health/live\nCMD [\"/app/beta\"]\n",
}


# Held for the process lifetime on purpose. Several detectors read files at DETECTION time
# rather than at Workspace construction, so a tree removed when a context manager exits is a
# tree they see as empty - and an empty tree is INDETERMINATE, which reads as "no finding".
# The first draft of this file did exactly that and reported nine passing controls that had
# never been given anything to look at.
_TREES: list[tempfile.TemporaryDirectory] = []


def run(overrides: dict[str, str] | None = None, drop: tuple[str, ...] = ()):
    holder = tempfile.TemporaryDirectory()
    _TREES.append(holder)
    root = pathlib.Path(holder.name)
    tree = dict(BASE_TREE)
    for key in drop:
        tree.pop(key, None)
    tree.update(overrides or {})
    for rel, text in tree.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return m.Workspace(root)


# --- conformant baseline ------------------------------------------------------------------

ws = run()
expect(len(ws.services) == 2, f"conformant: expected 2 services, got {len(ws.services)}")
expect(len(ws.registry) == 2, f"conformant: expected 2 registry entries, got {len(ws.registry)}")
expect(len(ws.repos_by_service) == 2,
       f"conformant: expected 2 repos, got {sorted(ws.repos_by_service)}")

for name, detector in (
    ("SP-0001", m.k8s_ports_internally_consistent),
    ("SP-0002", m.k8s_ports_match_registry),
    ("SP-0003", m.no_reserved_ports),
    ("SP-0004", m.dockerfile_ports_are_own),
    ("SP-0005", m.contract_ports_match_service),
    ("SP-0007", m.manifest_address_vars),
):
    finding = detector(ws)
    expect(finding.count == 0 and not finding.indeterminate,
           f"{name}: conformant tree produced {finding.count} finding(s): {finding.evidence}")

# SP-0006 is the one control a conformant-but-unmigrated tree must FAIL, because the fixture
# is deliberately on per-service ports. A pass here would mean the deferred control is inert.
expect(m.k8s_ports_are_constants(ws).count == 2,
       "SP-0006: expected both fixture services to be reported as unmigrated")


# --- SP-0001: the §11 atomicity invariant --------------------------------------------------

ws = run({"infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
          deployment_yaml([4002, 50060, 9102], 9999, {"PORT": 4002})})
finding = m.k8s_ports_internally_consistent(ws)
expect(finding.count == 1 and "probe targets 9999" in " ".join(finding.details),
       f"SP-0001: a probe on an unbound port must be caught; got {finding.details}")

ws = run({"infra/inboxxhq-infra/services/alpha-service/base/service.yaml":
          service_yaml("alpha-service", 4002, 50060, 9102, target_http=8080)})
finding = m.k8s_ports_internally_consistent(ws)
expect(any("targetPort=8080" in d for d in finding.details),
       f"SP-0001: port != targetPort must be caught; got {finding.details}")

ws = run({"infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
          deployment_yaml([8080, 50060, 9102], 8080, {"PORT": 8080})})
finding = m.k8s_ports_internally_consistent(ws)
expect(finding.count >= 1 and any("containerPort 8080" in d for d in finding.details),
       f"SP-0001: a half-migrated service must be caught; got {finding.details}")

ws = run({"infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
          deployment_yaml([4002, 50060, 9102], 4002, {"PORT": 8080})})
expect(any("PORT=8080" in d for d in m.k8s_ports_internally_consistent(ws).details),
       "SP-0001: a PORT env value no container binds must be caught")


# --- SP-0002: registry agreement ------------------------------------------------------------

ws = run({"infra/inboxxhq-infra/services/alpha-service/base/service.yaml":
          service_yaml("alpha-service", 8080, 50060, 9102),
          "infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
          deployment_yaml([8080, 50060, 9102], 8080, {"PORT": 8080})})
finding = m.k8s_ports_match_registry(ws)
expect(finding.count == 1 and "resolves callers to 4002" in " ".join(finding.details),
       f"SP-0002: manifest ahead of the registry must be caught; got {finding.details}")

ws = run(drop=("shared/platform-shared-go/platform/servicediscovery/ports.generated.go",))
expect(m.k8s_ports_match_registry(ws).indeterminate,
       "SP-0002: an absent registry must be INDETERMINATE, never a pass")

# A component with no registry entry is scrape-only infrastructure, not a violation.
ws = run({"infra/inboxxhq-infra/services/kafka-exporter/base/service.yaml":
          service_yaml("kafka-exporter", 9308, 9309, 9310)})
finding = m.k8s_ports_match_registry(ws)
expect(finding.count == 0 and any("kafka-exporter" in d for d in finding.details),
       f"SP-0002: an unregistered component must be reported, not counted; got {finding}")


# --- SP-0003: reserved ports ----------------------------------------------------------------

ws = run({"infra/inboxxhq-infra/services/alpha-service/base/service.yaml":
          service_yaml("alpha-service", 9090, 50060, 9102)})
expect(m.no_reserved_ports(ws).count >= 1,
       "SP-0003: publishing Prometheus's 9090 must be caught")

ws = run({"infra/inboxxhq-infra/services/alpha-service/overlays/dev/deployment.yaml":
          deployment_yaml([4002, 50060, 5432], 4002, {"PORT": 4002})})
expect(m.no_reserved_ports(ws).count >= 1,
       "SP-0003: binding PostgreSQL's 5432 as a containerPort must be caught")


# --- SP-0004: a Dockerfile names only its own ports -----------------------------------------

ws = run({"services/alpha/inboxxhq-alpha-service/Dockerfile":
          "FROM alpine:3.24\nEXPOSE 4003\n"
          "HEALTHCHECK CMD wget -q http://localhost:4003/health/live\nCMD [\"/app/alpha\"]\n"})
finding = m.dockerfile_ports_are_own(ws)
expect(finding.count >= 1 and "belongs to beta-service" in " ".join(finding.details),
       f"SP-0004: exposing another service's port must name the owner; got {finding.details}")

ws = run({"services/alpha/inboxxhq-alpha-service/Dockerfile":
          "FROM alpine:3.24\nEXPOSE 4002\n"
          "HEALTHCHECK CMD wget -q http://localhost:9999/health/live\nCMD [\"/app/alpha\"]\n"})
expect(m.dockerfile_ports_are_own(ws).count >= 1,
       "SP-0004: a HEALTHCHECK on a port the service does not publish must be caught")

# The identity rule that makes SP-0004 usable: a repository directory name is not a service
# name. inboxxhq-notification-service-ctx holds notification-service, and reading the
# directory instead of the contract turns a correct repository into a false finding.
ws = run({"services/alpha/inboxxhq-alpha-service-ctx/service.contract.yaml":
          "service:\n  name: alpha-service\n  ports:\n    http: 4002\n",
          "services/alpha/inboxxhq-alpha-service-ctx/Dockerfile":
          "FROM alpine:3.24\nEXPOSE 4002\n"
          "HEALTHCHECK CMD wget -q http://localhost:4002/health/live\nCMD [\"/app/a\"]\n"})
expect(m.dockerfile_ports_are_own(ws).count == 0,
       "SP-0004: a variant repo declaring its real service name must not be a finding")


# --- SP-0005: contract agreement ------------------------------------------------------------

ws = run({"services/alpha/inboxxhq-alpha-service/service.contract.yaml":
          "service:\n  name: alpha-service\n  ports:\n    http: 4031\n    grpc: 50060\n"})
finding = m.contract_ports_match_service(ws)
expect(finding.count == 1 and "publishes 4002" in " ".join(finding.details),
       f"SP-0005: a contract disagreeing with the manifest must be caught; got {finding.details}")

ws = run({"services/beta/inboxxhq-beta-service/service.contract.yaml":
          "name: beta-service\nports:\n  http: 4003\n  grpc: 50061\n  websocket: 4002\n"})
finding = m.contract_ports_match_service(ws)
expect(finding.count == 1 and "belongs to alpha-service" in " ".join(finding.details),
       f"SP-0005: a contract claiming another service's port must name it; got {finding.details}")

ws = run({"docs/core-docs/catalog/services/alpha-service.yaml":
          "name: alpha-service\ncanonical_port: 4031\n"})
finding = m.contract_ports_match_service(ws)
expect(finding.count == 1 and "canonical_port=4031" in " ".join(finding.details),
       f"SP-0005: a drifted catalog canonical_port must be caught; got {finding.details}")

ws = run({"docs/core-docs/catalog/services/alpha-service.yaml":
          "name: alpha-service\ncanonical_port: 4002\n"})
finding = m.contract_ports_match_service(ws)
expect(finding.count == 0 and "canonical_port(s) agree" in finding.evidence,
       f"SP-0005: an agreeing canonical_port must be credited in the evidence; got {finding}")

ws = run()
expect("catalog was not in the workspace" in m.contract_ports_match_service(ws).evidence,
       "SP-0005: an absent catalog must be stated, not silently treated as agreement")

# Both live contract shapes must be read. The top-level form is beta's; if only one shape
# parsed, half the fleet would be silently skipped and the control would report clean.
ws = run()
declared, _ = m._contract_ports(ws.root / "services/beta/inboxxhq-beta-service")
expect(declared == {"http": 4003, "grpc": 50061},
       f"SP-0005: top-level `ports:` contract shape must parse; got {declared}")
declared, _ = m._contract_ports(ws.root / "services/alpha/inboxxhq-alpha-service")
expect(declared == {"http": 4002, "grpc": 50060},
       f"SP-0005: nested `service.ports:` contract shape must parse; got {declared}")


# --- SP-0007: advisory address-variable cross-check ------------------------------------------

ws = run({"infra/inboxxhq-infra/services/alpha-service/overlays/dev/configmap-patch.yaml":
          "data:\n  x: y\nenv:\n  - name: BETA_SERVICE_URL\n    value: http://beta:4003\n"})
expect(m.manifest_address_vars(ws).count == 1,
       "SP-0007: a manifest address variable must be counted")

ws = run({"infra/inboxxhq-infra/services/alpha-service/overlays/dev/configmap-patch.yaml":
          "env:\n  - name: KUBERNETES_SERVICE_HOST\n    value: x\n"
          "  - name: BETA_USE_GRPC\n    value: 'true'\n"
          "  - name: CHECKOUT_SUCCESS_URL\n    value: https://example.test\n"})
expect(m.manifest_address_vars(ws).count == 0,
       "SP-0007: transport toggles, the Kubernetes API host and external URLs are not addresses")


# --- catalog wiring ---------------------------------------------------------------------------

catalog = yaml.safe_load(CONTROLS.read_text(encoding="utf-8"))
ids = [c["id"] for c in catalog["controls"]]
expect(len(ids) == len(set(ids)), "catalog: duplicate control id")
for control in catalog["controls"]:
    expect(control["detector"] in m.DETECTORS,
           f"catalog: {control['id']} names unknown detector {control['detector']!r}")
    for field in m.REQUIRED_FIELDS:
        expect(bool(control.get(field)), f"catalog: {control['id']} missing {field}")
    expect(control["status"] in m.VALID_STATUS,
           f"catalog: {control['id']} has invalid status {control['status']!r}")
expect(sum(1 for c in catalog["controls"] if c["status"] == "deferred") == 1,
       "catalog: exactly one control (SP-0006) should be deferred")

# A deferred control must never be enforced, and must never be baselined - freezing SP-0006
# would let the fleet drift one service further from §4.1 with the gate still green.
ws = run()
results = m.evaluate(ws, catalog["controls"], {})
deferred = [r for r in results if r["control"] == "SP-0006"]
expect(deferred and deferred[0]["result"] == "deferred",
       f"wiring: SP-0006 must evaluate to 'deferred'; got {deferred}")
expect(not any(m.enforced(r, m.SEVERITY_ORDER["critical"]) for r in results
               if r["control"] == "SP-0006"),
       "wiring: a deferred control must never be enforced")

report = m.build_report(ws, results, catalog, "major", m.SEVERITY_ORDER["major"])
expect(report["deferred"] == 1, f"wiring: report should count 1 deferred; got {report}")
expect(report["ok"],
       f"wiring: a conformant tree must pass even with 39 services unmigrated, because "
       f"SP-0006 is deferred; got {report['enforced_failures']} enforced failure(s)")

# ...and an unbaselined finding must still fail it, or the whole lane is decorative.
dirty = run({"services/alpha/inboxxhq-alpha-service/service.contract.yaml":
             "service:\n  name: alpha-service\n  ports:\n    http: 4031\n"})
dirty_report = m.build_report(dirty, m.evaluate(dirty, catalog["controls"], {}), catalog,
                              "major", m.SEVERITY_ORDER["major"])
expect(not dirty_report["ok"],
       "wiring: an unbaselined SP-0005 finding must fail the report")

# The ratchet: the same finding, frozen, passes; and one MORE than the baseline fails.
frozen = m.build_report(dirty, m.evaluate(dirty, catalog["controls"], {"SP-0005": 1}),
                        catalog, "major", m.SEVERITY_ORDER["major"])
expect(frozen["ok"], "wiring: a frozen finding must not fail the gate")
tightened = m.evaluate(dirty, catalog["controls"], {"SP-0005": 0})
expect(any(r["control"] == "SP-0005" and r["result"] == "fail" for r in tightened),
       "wiring: a count above the baseline must fail")
loosened = m.evaluate(run(), catalog["controls"], {"SP-0005": 3})
expect(any(r["control"] == "SP-0005" and r["result"] == "improved" for r in loosened),
       "wiring: a count below the baseline must report as improved")


if FAILURES:
    print(f"service-ports tests: {len(FAILURES)} FAILURE(S)")
    for failure in FAILURES:
        print(f"  - {failure}")
    raise SystemExit(1)
print("service-ports tests: all assertions passed")
